### ISSUE TITLE
Receiving Invalid Parameter Value When Specifying alert_policy

### ISSUE THREAD

**Issue by dthagard** [russellcardullo/go-pingdom#8]
This doesn't appear to be a supported attribute on the check types.
See https://www.pingdom.com/resources/api#MethodModify+Check & https://www.pingdom.com/resources/api#MethodCreate+New+Check

When creating a new HTTP check using the latest go-pingdom client, we receive the following error:
`400 Bad Request: Invalid parameter value: alert_policy`

**Comment by russellcardullo** [comment]
Yeah looking for more information on this but it seems that alert policies aren't enabled for all accounts?

https://help.pingdom.com/hc/en-us/articles/207571825-BeepManager-Incident-and-Alerts

In addition found this which looks like that feature will be removed entirely within the next few months: https://help.pingdom.com/hc/en-us/articles/115000728765-Moving-to-a-Simplified-Pingdom-Alerting-Experience

Since that feature will be going away anyway I think the right thing to do  is revert this change so the library works for all users regardless of the account type they have.
